[package]
name = "hyperscale-vm-manifest-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Fluent client-side construction of manifest graphs"

[dependencies]
hyperscale-hbor.workspace = true
hyperscale-vm-effects.workspace = true
hyperscale-vm-types.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
trybuild.workspace = true

[lints]
workspace = true
